name: 'lab04-actions'
on:
   push:
     branches:
       - lab04_master
jobs:
  build:
    runs-on: windows-latest
   
    steps:      
      - name: Git clone
        uses: actions/checkout@v1 
         
      - name: Git checkout
        run : git checkout Lab004_TIMP_master
         
      - name: Git pull
        run : git pull origin Lab004_TIMP_master
     
      - name: Test_formatter_lib
        working-directory: formatter_lib
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
          
      - name: Test_formatter_ex_lib
        working-directory: formatter_ex_lib
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
          
      - name: Test_hello_world_application
        working-directory: hello_world_application
        shell: bash
        run: |
          cmake -H. -B_build
          cmake --build _build
