name: 'Lab004_TIMP-actions'
on:
  push:

jobs:
  build:
    runs-on: windows-latest
  
    steps:      
      - name: Git clone
        uses: actions/checkout@v3
        with:
          ref: Lab004_TIMP_master
        
      - name: Git checkout
        run : git checkout Lab004_TIMP_master
        
      - name: Git pull
        run : git pull origin Lab004_TIMP_master
    
      - name: Test_formatter_lib
        working-directory: formatter_lib
        shell: cmd
        run: |
          cmake -H. -B_build
          cmake --build _build
          
      - name: Test_formatter_ex_lib
        working-directory: formatter_ex_lib
        shell: cmd
        run: |
          cmake -H. -B_build
          cmake --build _build
          
      - name: Test_hello_world_application
        working-directory: hello_world_application
        shell: cmd
        run: |
          cmake -H. -B_build
          cmake --build _build